### PR TITLE
add info about recent neo4j versions

### PR DESCRIPTION
**Pull request by slicksammy**
I spent a lot of time today trying to set this up and turns out it won't work with the neo4j version I'm running (4.3.5)

### CODE REVIEW

**Comment by klobuczek** [comment]
The driver compatibility matrix is located at https://support.neo4j.com/hc/en-us/articles/115013134648-Neo4j-Supported-Versions
None of the official drivers duplicate this information in their own documentation.
Note: neo4j-ruby-driver 1.7 works as well with neo4j 4.0 in the context of activegraph but it is probably not fully compatible.

**Comment by slicksammy** [comment]
This is the main page on their site https://neo4j.com/developer/ruby/ and it does not link to the matrix. I don't understand the down side of adding this snippet. Imo even if it saves one person one hour it's still worth it.

**Comment by slicksammy** [comment]
Another idea is to put a link to the matrix instead

**Comment by slicksammy** [comment]
@klobuczek what do you think? can we add the matrix to the readme?

**Review by klobuczek — APPROVED** [review]

**Pull request merged**
